/* CMS DE DEMOSTRACIÓN. No implementa autenticación ni sincronización multiusuario.
   Las operaciones de producción deben autorizarse en un servidor, nunca aquí. */
'use strict';
(() => {
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const S=EnObraStore,U=EnObraUI,E=U.escape,root=$('#admin-app');let kind='projects',profile=null;
 const collections={projects:'Proyectos',properties:'Propiedades',news:'Noticias y eventos'};
 function choose(){root.innerHTML=`<div class="admin-entry"><p class="eyebrow">DOS PERFILES DE DEMOSTRACIÓN</p><h2>¿Con qué perfil deseas explorar?</h2><p>Esta selección identifica al editor del prototipo; no verifica identidad ni protege datos.</p><div class="profile-grid">${S.data.adminProfiles.map(p=>`<button class="profile-card" data-profile="${E(p.id)}"><span>${E(p.name)}</span><small>${E(p.role)}</small><strong>Entrar a la demostración →</strong></button>`).join('')}</div></div>`;$$('[data-profile]').forEach(b=>b.onclick=()=>{profile=S.data.adminProfiles.find(p=>p.id===b.dataset.profile);dashboard();});}
 function save(){const ok=S.save();U.toast(ok?'Cambios guardados en este navegador.':'No se pudo guardar: almacenamiento bloqueado o lleno. Exporta los datos antes de salir.');return ok;}
 function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 function dashboard(){root.innerHTML=`<div class="admin-toolbar"><div><strong>${E(profile.name)}</strong><p class="small muted">${E(profile.role)} · Sesión de demostración</p></div><button class="text-link" id="switch-profile">Cambiar perfil</button></div><div class="admin-tabs" role="group" aria-label="Sección de administración">${Object.entries(collections).map(([k,v])=>`<button data-tab="${k}" aria-pressed="${kind===k}">${v} <span>${S.data[k].length}</span></button>`).join('')}<button data-tab="settings" aria-pressed="${kind==='settings'}">Contacto y marca</button><button data-tab="guide" aria-pressed="${kind==='guide'}">Guía de uso</button></div><div id="admin-content"></div><div class="admin-backups"><h3>Respaldo y publicación del prototipo</h3><p>Exporta los datos para conservarlos. Para actualizar la carpeta del sitio, exporta data.js y reemplaza ese archivo. Los cambios de este panel no se publican en Internet.</p><div class="modal-actions"><button class="button secondary" id="export-json">Exportar respaldo JSON</button><button class="button secondary" id="export-js">Exportar data.js</button><label class="button secondary upload-label">Importar respaldo<input id="import-data" type="file" accept=".json,application/json"></label></div><p class="small muted" id="import-status" role="status"></p></div>`;
 $('#switch-profile').onclick=choose;$$('[data-tab]').forEach(b=>b.onclick=()=>{kind=b.dataset.tab;dashboard();});$('#export-json').onclick=()=>download('enobra-respaldo.json',JSON.stringify(S.data,null,2),'application/json');$('#export-js').onclick=()=>download('data.js','/* Datos exportados desde el prototipo local de EnObra. */\nwindow.ENOBRA = '+JSON.stringify(S.data,null,2)+';\n','text/javascript');
 $('#import-data').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>15*1024*1024)throw Error('El respaldo supera 15 MB.');const d=JSON.parse(await f.text());if(!validImport(d))throw Error('El archivo no tiene la estructura completa de un respaldo EnObra.');if(!confirm('¿Reemplazar los datos locales con este respaldo?'))return;S.data=d;save();dashboard();}catch(err){$('#import-status').textContent='No se importó: '+err.message;}finally{if($('#import-data'))$('#import-data').value='';}};
 if(kind==='settings')settings();else if(kind==='guide')guide();else listing();}
 function validImport(d){return S.valid(d)&&Array.isArray(d.company.phones)&&Array.isArray(d.institution.presentation)&&Array.isArray(d.institution.principles)&&typeof d.institution.vision==='string'&&typeof d.institution.mission==='string'&&Array.isArray(d.adminProfiles)&&d.adminProfiles.length===2&&d.adminProfiles.every(p=>p.id&&p.name)&&d.services.every(s=>s.id&&s.title&&Array.isArray(s.items))&&d.projects.every(p=>p.id&&typeof p.title==='string'&&Number.isFinite(+p.year)&&Array.isArray(p.images)&&p.images.every(i=>typeof i==='string'))&&d.properties.every(p=>p.id&&typeof p.title==='string'&&Number.isFinite(p.price)&&Array.isArray(p.images)&&typeof p.date==='string'&&typeof p.operation==='string')&&d.news.every(n=>n.id&&typeof n.title==='string'&&typeof n.description==='string'&&typeof n.image==='string');}
 function listing(){const items=S.data[kind];$('#admin-content').innerHTML=`<div class="section-heading admin-heading"><div><p class="eyebrow">CONTENIDO</p><h2>${collections[kind]}</h2></div><button class="button primary" id="new-record">Añadir ${kind==='projects'?'proyecto':kind==='properties'?'propiedad':'publicación'} +</button></div><div class="admin-records">${items.map(item=>`<article class="admin-row"><img src="${U.media(item.images?.[0]||item.image)}" alt=""><div><h3>${E(item.title)}</h3><p>${E(item.category||item.operation||'')} ${E(item.year||item.date||'')}${item.demo?' · Ejemplo':''}</p></div><div class="admin-row-actions"><button class="text-link" data-edit="${E(item.id)}">Editar</button><button class="text-link danger" data-delete="${E(item.id)}">Eliminar</button></div></article>`).join('')||'<p>No hay registros. Añade el primero.</p>'}</div>`;$('#new-record').onclick=()=>editor();$$('[data-edit]').forEach(b=>b.onclick=()=>editor(S.data[kind].find(x=>String(x.id)===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>{const item=S.data[kind].find(x=>String(x.id)===b.dataset.delete);if(confirm(`¿Eliminar “${item.title}” del catálogo local?`)){S.data[kind]=S.data[kind].filter(x=>x!==item);save();dashboard();}});}
 function input(name,label,value='',type='text',required=true){return `<label>${label}${required?' *':''}<input name="${name}" type="${type}" value="${E(value)}" ${required?'required':''} ${type==='number'?'min="0" step="any"':''}></label>`;}
 function textarea(name,label,value='',required=false){return `<label class="full">${label}${required?' *':''}<textarea name="${name}" ${required?'required':''}>${E(value)}</textarea></label>`;}
 function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(v=>`<option${value===v?' selected':''}>${E(v)}</option>`).join('')}</select></label>`;}
 function editor(existing){const item=existing?JSON.parse(JSON.stringify(existing)):null;const p=item||{title:'',description:'',images:[],renders:[],demo:true};let fields=input('title','Título',p.title)+textarea('description','Descripción completa',p.description,true);
 if(kind==='projects')fields+=input('year','Año',p.year||new Date().getFullYear(),'number')+input('category','Categoría',p.category||'')+input('country','País',p.country||'Guatemala');
 if(kind==='properties')fields+=select('operation','Operación',['Venta','Alquiler'],p.operation)+select('type','Tipo',['Casa','Apartamento','Terreno','Local'],p.type)+input('zone','Zona',p.zone)+input('location','Ubicación',p.location)+input('price','Precio (Q)',p.price??'','number')+input('rooms','Habitaciones',p.rooms??0,'number')+input('baths','Baños',p.baths??0,'number')+input('parking','Parqueos',p.parking??0,'number')+input('area','Superficie (m²)',p.area??'','number')+input('date','Fecha',p.date||new Date().toISOString().slice(0,10),'date')+textarea('commercial','Especificaciones comerciales',p.commercial||'',true);
 if(kind==='news')fields+=select('category','Categoría',['Anuncios','Eventos','Proyectos'],p.category)+input('date','Fecha',p.date||new Date().toISOString().slice(0,10),'date')+input('image','Imagen: ruta o URL HTTPS',p.image||'assets/estructura.jpg');
 else fields+=textarea('images','Fotografías: una ruta o URL HTTPS por línea',(p.images||[]).join('\n'),true)+textarea('renders','Renders: una ruta o URL HTTPS por línea',(p.renders||[]).join('\n'))+input('video','Video MP4/WebM: ruta o URL HTTPS',p.video||'','text',false);
 fields+=`<label class="full checkbox-label"><input type="checkbox" name="demo" ${p.demo?'checked':''}> Marcar este contenido como ejemplo</label>`;
 U.openModal(`<div class="modal-body"><p class="eyebrow">${collections[kind]}</p><h2 id="modal-title">${existing?'Editar contenido':'Nuevo contenido'}</h2><form id="record-form"><div class="form-grid">${fields}<div class="full upload-panel"><label>Cargar ${kind==='news'?'imagen':'fotos o renders'} desde tu equipo<input id="upload-media" type="file" accept="image/jpeg,image/png,image/webp,image/gif" ${kind==='news'?'':'multiple'}></label>${kind!=='news'?'<label>Destino de las imágenes<select id="upload-target"><option value="images">Fotografías</option><option value="renders">Renders</option></select></label>':''}<p class="small muted">JPEG, PNG, WebP o GIF. Máximo 2 MB por imagen en este prototipo. Para alta resolución y videos se recomienda alojamiento externo.</p><p id="upload-status" role="status"></p></div><p class="full error" id="record-error" role="alert"></p><button type="submit" class="button primary">Guardar cambios</button></div></form></div>`);
 let pendingUploads=false;
 $('#upload-media').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;pendingUploads=true;const button=$('#record-form button[type=submit]');button.disabled=true;$('#upload-status').textContent='Procesando imágenes…';try{if(files.some(f=>!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)||f.size>2*1024*1024))throw Error('Selecciona imágenes válidas de hasta 2 MB.');const encoded=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('No se pudo leer la imagen.'));r.readAsDataURL(f);})));const target=kind==='news'?'image':$('#upload-target').value;const field=$(`[name="${target}"]`,$('#record-form'));field.value=kind==='news'?encoded[0]:[field.value,...encoded].filter(Boolean).join('\n');$('#upload-status').textContent=`${encoded.length} imágenes añadidas. Guarda el registro para conservarlas.`;}catch(err){$('#upload-status').textContent=err.message;}finally{pendingUploads=false;button.disabled=false;}};
 $('#record-form').onsubmit=e=>{e.preventDefault();if(pendingUploads)return;const form=e.target,obj=Object.fromEntries(new FormData(form));obj.demo=form.elements.demo.checked;obj.id=p.id||(kind==='properties'?Date.now():kind+'-'+Date.now());obj.updatedBy=profile.id;obj.updatedAt=new Date().toISOString();['year','price','rooms','baths','parking','area'].forEach(k=>{if(k in obj)obj[k]=Number(obj[k]);});if(kind!=='news'){obj.images=obj.images.split('\n').map(s=>s.trim()).filter(Boolean);obj.renders=obj.renders.split('\n').map(s=>s.trim()).filter(Boolean);}const sources=kind==='news'?[obj.image]:[...obj.images,...obj.renders];if(sources.some(x=>U.media(x)==='assets/estructura.jpg'&&x!=='assets/estructura.jpg')){$('#record-error').textContent='Usa rutas assets/…, URLs HTTPS o imágenes cargadas desde el equipo.';return;}if(obj.video&&!/^(assets\/[\w./-]+\.(mp4|webm)|https:\/\/[^\s]+\.(mp4|webm)(\?[^\s]*)?)$/i.test(obj.video)){$('#record-error').textContent='El video debe ser un archivo MP4 o WebM, con ruta assets/… o URL HTTPS.';return;}if(existing){const index=S.data[kind].findIndex(x=>x.id===existing.id);S.data[kind][index]=obj;}else S.data[kind].unshift(obj);save();U.closeModal();dashboard();};
 }
 function settings(){const c=S.data.company;$('#admin-content').innerHTML=`<div class="admin-heading"><p class="eyebrow">CONFIGURACIÓN</p><h2>Contacto y marca.</h2><p>Completa únicamente datos confirmados por el cliente.</p></div><form id="settings-form"><div class="form-grid">${input('person','Responsable',c.person)}${input('address','Dirección',c.address)}${input('phone1','Teléfono',c.phones[0]||'')}${input('phone2','Teléfono adicional',c.phones[1]||'','text',false)}${input('whatsapp','WhatsApp con código 502',c.whatsapp)}${input('email','Correo institucional',c.email,'email',false)}${input('instagram','Instagram: URL HTTPS',c.instagram,'url',false)}${input('facebook','Facebook: URL HTTPS',c.facebook,'url',false)}${input('domain','Dominio: URL HTTPS',c.domain,'url',false)}${input('logo','Logo: ruta assets/ o URL HTTPS',c.logo,'text',false)}<p class="full small muted">El dominio se registra como referencia. Este formulario no compra, configura ni publica un dominio.</p><button type="submit" class="button primary">Guardar configuración</button><p id="settings-error" class="error full" role="alert"></p></div></form>`;$('#settings-form').onsubmit=e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));if(!/^502\d{8}$/.test(x.whatsapp)){$('#settings-error').textContent='WhatsApp debe contener 502 y los 8 dígitos del teléfono.';return;}if(['instagram','facebook','domain'].some(k=>x[k]&&!x[k].startsWith('https://'))){$('#settings-error').textContent='Los enlaces deben comenzar con https://.';return;}if(x.logo&&U.media(x.logo)==='assets/estructura.jpg'&&x.logo!=='assets/estructura.jpg'){$('#settings-error').textContent='Ruta del logo no válida.';return;}Object.assign(S.data.company,x,{phones:[x.phone1,x.phone2].filter(Boolean)});delete S.data.company.phone1;delete S.data.company.phone2;save();};}
 function guide(){$('#admin-content').innerHTML=`<article class="admin-guide prose"><p class="eyebrow">INDUCCIÓN AL CLIENTE</p><h2>Publicar contenido, paso a paso.</h2><ol><li>Selecciona Proyectos, Propiedades o Noticias.</li><li>Pulsa Añadir, completa los datos y carga fotografías. Para proyectos, indica el año; para propiedades, la operación y las especificaciones comerciales.</li><li>Añade renders en su campo específico. Las imágenes se muestran junto a las fotografías en la ficha.</li><li>Guarda y abre la página correspondiente para revisar el resultado. Las fechas y precios deben ser reales antes de retirar la marca de ejemplo.</li><li>Usa Editar para actualizar. Eliminar solicita confirmación.</li><li>Exporta un respaldo JSON para conservar una copia recuperable.</li><li>Exporta data.js para reemplazar el archivo en la carpeta del sitio. Las imágenes cargadas están incorporadas en los datos exportados.</li></ol><h3>Dos perfiles, una demostración</h3><p>El Ingeniero Bernardo y la Arquitecta tienen perfiles de demostración con las mismas opciones. Para acceso real se necesitan dos cuentas verificadas, autorización en servidor, base de datos compartida y almacenamiento multimedia.</p><h3>Antes de publicar</h3><p>Confirmar logo, correo, teléfonos, redes sociales, dominio y material del proyecto inmobiliario. Reemplazar los ejemplos, conectar formularios y programar la capacitación y revisión presencial con el cliente.</p><h3>Imágenes de alta resolución y videos</h3><p>El sitio admite imágenes mediante URLs HTTPS y videos MP4/WebM. Para producción, alojar los originales fuera del navegador. El límite de carga local es solo para esta demostración.</p><p>Si el navegador no comparte localStorage entre archivos locales, exporta data.js y sustitúyelo en la carpeta. Para colaboración real entre dispositivos se requiere backend.</p></article>`;}
 choose();
})();
