'use strict';
(() => {
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const D=EnObraStore.data;
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const paths = {
    heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
    pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
    bed:'<path d="M3 19V5m18 14V9M3 15h18M3 9h5v6m0-6h10a3 3 0 0 1 3 3v3"/>',
    bath:'<path d="M3 12h18v3a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5Zm3 0V5a3 3 0 0 1 6 0M7 20v2m10-2v2"/>',
    car:'<path d="m4 10 2-6h12l2 6M3 10h18v8H3Zm2 8v3m14-3v3M6 14h2m8 0h2"/>',
    area:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6M3 3l6 6m12-6-6 6M3 21l6-6m12 6-6-6"/>',
    helmet:'<path d="M3 16a9 9 0 0 1 6-9m6 0a9 9 0 0 1 6 9M9 12V4h6v8M2 16h20v4H2Z"/>',
    roller:'<rect x="3" y="3" width="14" height="7" rx="1"/><path d="M17 6h4v8H11v3m-2 0h4v6H9Z"/>',
    check:'<rect x="5" y="4" width="15" height="18" rx="2"/><path d="M9 4V2h7v2M8 10l2 2 4-4m-6 9 2 2 4-4"/>',
    leaf:'<path d="M20 3C7 1 1 8 5 16s18 6 15-13ZM5 21 16 8M9 17v-6m0 6h6"/>'
  };
  const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.check}</svg>`;
const readStore=(k,f)=>EnObraStore.read(k,f),writeStore=(k,v)=>EnObraStore.write(k,v);
const media=url=>/^(assets\/[\w.\/-]+|https:\/\/[^\s]+|data:image\/(png|jpeg|webp|gif);base64,[a-zA-Z0-9+/=]+)$/.test(url||'')?escape(url):'assets/estructura.jpg';
const link=url=>/^https:\/\/[^\s]+$/.test(url||'')?escape(url):'';
const money=p=>`Q ${new Intl.NumberFormat('en-US').format(p.price)}${p.operation==='Alquiler'?' <small>/ mes</small>':''}`;
const wa=(text)=>`https://wa.me/${String(D.company.whatsapp).replace(/\D/g,'')}?text=${encodeURIComponent(text)}`;
const fav=readStore('enobra-favorites',[]), favorites=new Set(Array.isArray(fav)?fav:[]);
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function features(p){return `<div class="features">${[['bed',p.rooms,'habitaciones'],['bath',p.baths,'baños'],['car',p.parking,'parqueos'],['area',p.area+' m²',p.type==='Terreno'?'de terreno':'de construcción']].map(([i,v,t])=>`<span title="${t}" aria-label="${v} ${t}">${icon(i)}${v}</span>`).join('')}</div>`;}
const contact=`<p>${escape(D.company.person)}</p><p>${escape(D.company.address)}</p><p>${D.company.phones.map(p=>`<a href="tel:+502${p.replace(/\D/g,'')}">${escape(p)}</a>`).join(' · ')}</p><p>${D.company.email?`<a href="mailto:${escape(D.company.email)}">${escape(D.company.email)}</a>`:'Correo institucional: pendiente de confirmar.'}</p><a class="text-link" target="_blank" rel="noopener" href="${wa('Hola, quisiera información sobre los servicios de EnObra.')}">Escríbenos por WhatsApp ↗</a>${['instagram','facebook'].filter(k=>link(D.company[k])).map(k=>`<p><a href="${link(D.company[k])}" target="_blank" rel="noopener">${k==='instagram'?'Instagram':'Facebook'} ↗</a></p>`).join('')}`;
$$('.contact-info').forEach(el=>el.innerHTML=contact);$('#year').textContent=new Date().getFullYear();
if(D.company.logo)$$('.brand').forEach(el=>el.innerHTML=`<img class="official-logo" src="${media(D.company.logo)}" alt="EnObra">`);
const current=location.pathname.split('/').pop()||'index.html';$$('#navigation a').forEach(a=>{const active=a.getAttribute('href')===current||(current==='proyecto.html'&&a.getAttribute('href')==='proyectos.html')||(current==='propiedad.html'&&a.getAttribute('href')==='bienes-raices.html')||(current==='noticia.html'&&a.getAttribute('href')==='noticias.html');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');});
const nav=$('#navigation'),menu=$('#menu-toggle');function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');}
menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');};
document.addEventListener('click',e=>{if(!$('#header').contains(e.target))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});window.addEventListener('resize',()=>{if(innerWidth>768)closeMenu();});
const onScroll=()=>{$('#header').classList.toggle('scrolled',scrollY>30);$('#back-top').hidden=scrollY<600;};window.addEventListener('scroll',onScroll,{passive:true});onScroll();$('#back-top').onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});$('.brand').focus({preventScroll:true});};
const modal=$('#modal');let returnFocus=null;
function openModal(html){if(!modal.open){returnFocus=document.activeElement;modal.showModal();document.body.classList.add('modal-open');}$('#modal-content').innerHTML=html;requestAnimationFrame(()=>($('[autofocus]',modal)||$('#modal-close')).focus());}
$('#modal-close').onclick=()=>modal.close();modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
modal.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const els=$$('button:not(:disabled),a[href],input,select,textarea',modal).filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}});
window.EnObraUI={escape,media,toast,openModal,closeModal:()=>modal.close()};
// Home: previews only. Full content lives on independent HTML pages.
function projectCard(p){return `<a class="project-card" href="proyecto.html?id=${encodeURIComponent(p.id)}"><div class="project-image"><img src="${media(p.images[0])}" alt="${escape(p.title)}${p.demo?' · imagen de ejemplo':''}" loading="lazy"><span>Ver proyecto ↗</span></div><h3>${escape(p.title)}</h3><p>${escape(p.category)} · ${escape(p.year)}${p.demo?' · Ejemplo':''}</p></a>`;}
function newsCard(n){return `<a class="news-card" href="noticia.html?id=${encodeURIComponent(n.id)}"><img src="${media(n.image)}" alt="${escape(n.title)}" loading="lazy"><div><p class="eyebrow">${escape(n.category)}${n.demo?' · EJEMPLO':''}</p><h3>${escape(n.title)}</h3><p>${escape(n.description.slice(0,115))}…</p><span class="text-link">Leer más →</span></div></a>`;}
if($('#home-projects'))$('#home-projects').innerHTML=D.projects.slice(0,3).map(projectCard).join('');
if($('#home-news'))$('#home-news').innerHTML=D.news.slice(0,2).map(newsCard).join('');
if($('#news-grid'))$('#news-grid').innerHTML=D.news.map(newsCard).join('')||'<p>No hay publicaciones por el momento.</p>';
if($('#presentation')){const I=D.institution;$('#presentation').innerHTML=I.presentation.map(p=>`<p>${escape(p)}</p>`).join('');$('#signature').innerHTML=`<strong>${escape(I.signature)}</strong><br>${escape(I.role)}<br>EnObra`;$('#mission').textContent=I.mission;$('#vision').innerHTML=I.vision.split('\n\n').map(p=>`<p>${escape(p)}</p>`).join('');$('#principles').innerHTML=I.principles.map((p,i)=>`<article><span class="principle-number">0${i+1}</span><h3>${escape(p.title)}</h3><p>${escape(p.description)}</p></article>`).join('');}
if($('#service-list'))$('#service-list').innerHTML=D.services.map((s,i)=>`<article id="${escape(s.id)}" class="service-feature${i%2?' service-feature--reverse':''}${i===3?' service-feature--dark':''}"><div class="service-visual"><span class="service-visual-number">0${i+1}</span><div class="service-image-frame"><img class="parallax-media" data-parallax="0.025" src="${media(s.image)}" alt="Referencia visual de ${escape(s.title)}" loading="lazy" decoding="async"></div><span class="service-image-caption">ENOBRA · SERVICIO 0${i+1}</span></div><div class="service-content"><div class="service-kicker"><span>0${i+1}</span><i></i><small>ETAPA DEL PROYECTO</small></div><h2>${escape(s.title)}</h2><p class="service-lead">${escape(s.short)}</p><div class="service-scope"><p>ALCANCE DEL SERVICIO</p><ul>${s.items.map(t=>`<li>${escape(t)}</li>`).join('')}</ul></div><a class="service-cta" href="contacto.html?asunto=${encodeURIComponent(s.title)}"><span>Consultar este servicio</span><b aria-hidden="true">↗</b></a></div></article>`).join('');
if($('.service-index-nav')&&'IntersectionObserver' in window){const links=$$('.service-index-nav a');const sections=$$('.service-feature');const sectionSpy=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;links.forEach(a=>a.toggleAttribute('aria-current',a.getAttribute('href')==='#'+visible.target.id));},{rootMargin:'-25% 0px -55% 0px',threshold:[0,.15,.4,.7]});sections.forEach(s=>sectionSpy.observe(s));}
if($('#project-year')){[...new Set(D.projects.map(p=>p.year))].sort((a,b)=>b-a).forEach(y=>$('#project-year').add(new Option(y,y)));function render(){const a=D.projects.filter(p=>!$('#project-year').value||String(p.year)===$('#project-year').value);$('#projects-grid').innerHTML=a.map(projectCard).join('');$('#project-count').textContent=`${a.length} proyectos`;}$('#project-year').onchange=render;render();}
// Catalog filters and favorites.
function propertyCard(p){return `<article class="property-card"><div class="property-photo"><img src="${media(p.images[0])}" alt="${escape(p.title)}${p.demo?' · ejemplo':''}" loading="lazy"><span class="badge ${p.operation==='Alquiler'?'rental':''}">En ${escape(p.operation.toLowerCase())}</span><button class="icon-button favorite" data-favorite="${p.id}" aria-pressed="${favorites.has(p.id)}" aria-label="Favorito: ${escape(p.title)}">${icon('heart')}</button></div><div class="property-body"><p class="price">${money(p)}</p><h3>${escape(p.title)}</h3><p class="location">${icon('pin')}${escape(p.zone)} · ${escape(p.location)}</p>${features(p)}<div class="property-actions"><a class="property-detail-link" href="propiedad.html?id=${encodeURIComponent(p.id)}">Ver detalles →</a><a class="whatsapp" href="${wa('Hola, quisiera consultar sobre '+p.title)}" target="_blank" rel="noopener">Consultar por WhatsApp</a></div></div></article>`;}
let renderProperties=null;
if($('#properties-grid')){
const base={operation:'',type:'',zone:'',min:'',max:'',q:'',sort:'recent',favorites:false};let state={...base};const map={type:'type',zone:'zone',min:'price-min',max:'price-max',q:'property-search',sort:'sort'};
[...new Set(D.properties.map(p=>p.zone))].sort().forEach(z=>$('#zone').add(new Option(z,z)));
function sync() {Object.entries(map).forEach(([k,id])=>$('#'+id).value=state[k]);$('#favorites-only').checked=state.favorites;$$('[data-operation]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.operation===state.operation));}
function url(){const p=new URLSearchParams();Object.keys(base).forEach(k=>{if(state[k]!==base[k])p.set(k,state[k]);});try{history.replaceState(null,'',location.pathname+(p.size?'?'+p:''));}catch{}}
renderProperties=()=>{let items=D.properties.filter(p=>(!state.operation||p.operation===state.operation)&&(!state.type||p.type===state.type)&&(!state.zone||p.zone===state.zone)&&(state.min===''||p.price>=+state.min)&&(state.max===''||p.price<=+state.max)&&(!state.favorites||favorites.has(p.id))&&normalize(`${p.title} ${p.zone} ${p.location} ${p.type}`).includes(normalize(state.q)));items.sort((a,b)=>state.sort==='asc'?a.price-b.price:state.sort==='desc'?b.price-a.price:b.date.localeCompare(a.date));$('#properties-grid').innerHTML=items.map(propertyCard).join('');$('#result-count').textContent=`Mostrando ${items.length} de ${D.properties.length} propiedades`;$('#favorite-count').textContent=favorites.size;$('#empty').hidden=!!items.length;};
const params=new URLSearchParams(location.search);Object.keys(base).forEach(k=>{if(params.has(k))state[k]=k==='favorites'?params.get(k)==='true':params.get(k);});sync();renderProperties();
Object.entries(map).forEach(([k,id])=>$('#'+id).oninput=e=>{state[k]=e.target.value;renderProperties();url();});$('#favorites-only').onchange=e=>{state.favorites=e.target.checked;renderProperties();url();};$$('[data-operation]').forEach(b=>b.onclick=()=>{state.operation=b.dataset.operation;sync();renderProperties();url();});
function reset(){state={...base};sync();renderProperties();url();}$('#clear-filters').onclick=reset;$$('[data-reset]').forEach(b=>b.onclick=reset);if(innerWidth<=768)$('.filters').open=false;
$('#share-filters').onclick=async()=>{url();if(location.protocol!=='file:'){try{await navigator.clipboard.writeText(location.href);toast('Enlace copiado');return;}catch{}}openModal(`<div class="modal-body"><h2 id="modal-title">Comparte tu búsqueda</h2><p>${location.protocol==='file:'?'Este enlace es local. Para compartirlo entre dispositivos, publica el sitio en un dominio.':'Copia este enlace:'}</p><input id="copy-link" readonly aria-label="Enlace de búsqueda" value="${escape(location.href)}"><button class="text-link" id="select-link">Seleccionar enlace</button></div>`);$('#select-link').onclick=()=>{$('#copy-link').focus();$('#copy-link').select();};};
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-favorite]');if(!b)return;const id=D.properties.find(p=>String(p.id)===b.dataset.favorite)?.id;if(id===undefined)return;favorites.has(id)?favorites.delete(id):favorites.add(id);const ok=writeStore('enobra-favorites',[...favorites]);if(renderProperties){renderProperties();($(`[data-favorite="${id}"]`)||$('#favorites-only')).focus({preventScroll:true});}toast('Favoritos actualizados'+(ok?'':' · Solo durante esta sesión'));});
// Dedicated project and property detail pages, including image / render gallery.
function gallery(item){const images=[...(item.images||[]),...(item.renders||[])];if(!images.length)return '';return `<div class="detail-gallery"><img id="detail-image" src="${media(images[0])}" alt="${escape(item.title)} · imagen 1"><div class="detail-gallery-controls"><button class="icon-button" id="image-prev" aria-label="Imagen anterior">←</button><span id="image-counter" aria-live="polite">1 / ${images.length}</span><button class="icon-button" id="image-next" aria-label="Imagen siguiente">→</button></div></div><div class="thumbnails">${images.map((img,i)=>`<button data-image="${i}" aria-label="Ver ${i>=(item.images||[]).length?'render':'imagen'} ${i+1}" aria-pressed="${i===0}"><img src="${media(img)}" alt="" loading="lazy"></button>`).join('')}</div>`;}
function bindGallery(item){const imgs=[...(item.images||[]),...(item.renders||[])];let i=0;if(!imgs.length)return;function show(n){i=(n+imgs.length)%imgs.length;$('#detail-image').src=imgs[i];$('#detail-image').alt=item.title+' · imagen '+(i+1);$('#image-counter').textContent=`${i+1} / ${imgs.length}`;$$('[data-image]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.image===i));}$('#image-prev').onclick=()=>show(i-1);$('#image-next').onclick=()=>show(i+1);$$('[data-image]').forEach(b=>b.onclick=()=>show(+b.dataset.image));}
function optionalVideo(item){return item.video&&/^(assets\/[\w./-]+\.(mp4|webm)|https:\/\/[^\s]+\.(mp4|webm)(\?[^\s]*)?)$/i.test(item.video)?`<h2>Video del proyecto</h2><video controls preload="metadata" src="${escape(item.video)}">Tu navegador no admite video.</video>`:'';}
const id=new URLSearchParams(location.search).get('id');
if($('#project-detail')){const p=D.projects.find(p=>String(p.id)===id);if(!p)$('#project-detail').innerHTML='<h1>Proyecto no encontrado</h1><a class="text-link" href="proyectos.html">Volver al portafolio →</a>';else{$('#project-detail').innerHTML=`<a class="breadcrumb" href="proyectos.html">← Portafolio de construcción</a><p class="eyebrow">${escape(p.year)} · ${escape(p.category)}</p><h1>${escape(p.title)}</h1><p>${escape(p.country)}${p.demo?' · Proyecto e imágenes de ejemplo':''}</p>${gallery(p)}<div class="detail-description"><h2>Acerca del proyecto</h2><p class="prose">${escape(p.description)}</p>${!(p.renders||[]).length?'<p class="small muted">Renders del proyecto: pendientes de recibir.</p>':''}${optionalVideo(p)}<a class="button primary" href="contacto.html?asunto=Construcci%C3%B3n">Conversemos sobre tu proyecto →</a></div>`;bindGallery(p);document.title=p.title+' | EnObra';}}
if($('#property-detail')){const p=D.properties.find(p=>String(p.id)===id);if(!p)$('#property-detail').innerHTML='<h1>Propiedad no encontrada</h1><a class="text-link" href="bienes-raices.html">Volver al catálogo →</a>';else{$('#property-detail').innerHTML=`<a class="breadcrumb" href="bienes-raices.html">← Bienes raíces</a><p class="eyebrow">${escape(p.operation)} · ${escape(p.type)}${p.demo?' · EJEMPLO':''}</p><h1>${escape(p.title)}</h1><p>${escape(p.zone)} · ${escape(p.location)}</p>${gallery(p)}<div class="property-detail-columns"><article><h2>Un lugar para tu próximo capítulo.</h2><p class="prose">${escape(p.description)}</p><h3>Especificaciones comerciales</h3><p class="prose">${escape(p.commercial)}</p>${!(p.renders||[]).length?'<p class="small muted">Renders: pendientes de recibir.</p>':''}${optionalVideo(p)}</article><aside class="property-summary"><div class="price">${money(p)}</div>${features(p)}<button class="button primary" id="request-visit">Solicitar visita →</button><a class="text-link" href="${wa('Hola, quisiera consultar sobre '+p.title)}" target="_blank" rel="noopener">Consultar por WhatsApp ↗</a></aside></div>`;bindGallery(p);$('#request-visit').onclick=()=>openVisit(p);document.title=p.title+' | EnObra';}}
if($('#news-detail')){const n=D.news.find(n=>n.id===id);$('#news-detail').innerHTML=n?`<a class="breadcrumb" href="noticias.html">← Noticias y eventos</a><p class="eyebrow">${escape(n.category)} · ${escape(n.date)}${n.demo?' · EJEMPLO':''}</p><h1>${escape(n.title)}</h1><img class="news-cover" src="${media(n.image)}" alt="${escape(n.title)}"><p class="prose article-text">${escape(n.description)}</p>`:'<h1>Publicación no encontrada</h1><a class="text-link" href="noticias.html">Ver noticias →</a>';}
// Forms validate locally and explicitly simulate delivery.
const subjects=[...D.services.map(s=>s.title),'Bienes raíces','Otro'];
function field(prefix,name,label,type='text'){return `<label>${label} *<input id="${prefix}-${name}" name="${name}" type="${type}" required ${name==='phone'?'inputmode="tel"':''} aria-describedby="${prefix}-${name}-error"><span class="error" id="${prefix}-${name}-error"></span></label>`;}
function formHTML(prefix,subject='',property=null){return `<form class="request-form" data-prefix="${prefix}" ${property?`data-property="${escape(property.title)}"`:''} novalidate><div class="form-result" role="status"></div><div class="form-grid">${field(prefix,'name','Nombre')}${property?'':field(prefix,'email','Correo electrónico','email')}${field(prefix,'phone','Teléfono')}${property?field(prefix,'date','Fecha preferida','date'):`<label>Tipo de consulta<select name="subject" id="${prefix}-subject">${subjects.map(s=>`<option${s===subject?' selected':''}>${escape(s)}</option>`).join('')}</select></label><label class="full">Mensaje *<textarea id="${prefix}-message" name="message" required aria-describedby="${prefix}-message-error"></textarea><span class="error" id="${prefix}-message-error"></span></label>`}<p class="form-note full">Demostración: la solicitud se guarda en este navegador. No se envía a EnObra.</p><button type="submit" class="button primary full">Simular ${property?'solicitud de visita':'envío'} →</button></div></form>`;}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function openVisit(p){openModal(`<div class="modal-body"><p class="eyebrow">SOLICITUD DE VISITA</p><h2 id="modal-title">${escape(p.title)}</h2>${formHTML('visit','',p)}</div>`);$('#visit-date').min=today();}
if($('#contact-form-container'))$('#contact-form-container').innerHTML=formHTML('contact',new URLSearchParams(location.search).get('asunto')||'Diseño');
function validate(f){let error='';const v=f.value.trim();if(!v)error='Completa este campo.';else if(f.name==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))error='Ingresa un correo válido.';else if(f.name==='phone'&&!/^\d{8}$/.test(v.replace(/[\s-]/g,'')))error='Ingresa un teléfono de Guatemala de 8 dígitos.';else if(f.name==='date'&&v<today())error='Elige hoy o una fecha futura.';f.setAttribute('aria-invalid',!!error);$('#'+f.id+'-error').textContent=error;return !error;}
document.addEventListener('submit',async e=>{if(!e.target.matches('.request-form'))return;e.preventDefault();const form=e.target,fields=$$('input,textarea',form),ok=fields.map(validate);if(ok.includes(false)){fields[ok.indexOf(false)].focus();return;}const b=$('button[type=submit]',form),label=b.innerHTML,data=Object.fromEntries(new FormData(form));data.property=form.dataset.property||null;data.createdAt=new Date().toISOString();b.disabled=true;b.innerHTML='<span class="spinner"></span> Guardando…';
// CONECTAR API REAL AQUÍ. No se realiza ningún envío remoto en el prototipo.
await new Promise(r=>setTimeout(r,650));const saved=writeStore('enobra-last-submission',data);try{const L=JSON.parse(localStorage.getItem('enobra-messages')||'[]');L.unshift({id:'m-'+Date.now(),status:'pending',...data});localStorage.setItem('enobra-messages',JSON.stringify(L.slice(0,500)));}catch{}form.reset();b.disabled=false;b.innerHTML=label;const result=$('.form-result',form);result.className='form-result form-success';result.textContent='Simulación completada. '+(saved?'Guardada en este navegador.':'Almacenamiento bloqueado: solo disponible en esta sesión.')+' No se envió a la empresa.';toast('Simulación completada');});
document.addEventListener('input',e=>{if(e.target.closest('.request-form')&&e.target.getAttribute('aria-invalid')==='true')validate(e.target);});
// Global search navigates to independent pages.
$('#search-open').onclick=()=>{closeMenu();openModal('<div class="modal-body"><p class="eyebrow">EXPLORA ENOBRA</p><h2 id="modal-title">¿Qué estás buscando?</h2><label>Buscar<input id="global-search" type="search" autofocus placeholder="Proyectos, propiedades, servicios…"></label><p id="search-status" role="status"></p><div id="search-results" class="search-results"></div></div>');function search(){const q=normalize($('#global-search').value);let count=0;$('#search-results').innerHTML=[['Servicios',D.services,s=>'servicios.html#'+encodeURIComponent(s.id)],['Proyectos',D.projects,p=>'proyecto.html?id='+encodeURIComponent(p.id)],['Propiedades',D.properties,p=>'propiedad.html?id='+encodeURIComponent(p.id)],['Noticias',D.news,n=>'noticia.html?id='+encodeURIComponent(n.id)]].map(([name,items,url])=>{const found=items.filter(x=>normalize(`${x.title} ${x.type||''} ${x.zone||''} ${x.short||''}`).includes(q));count+=found.length;return found.length?`<h3>${name}</h3>${found.map(x=>`<a class="search-result" href="${url(x)}">${escape(x.title)} <span>↗</span></a>`).join('')}`:'';}).join('');$('#search-status').textContent=count?`${count} resultados`:'Sin coincidencias.';}$('#global-search').oninput=search;search();};
// Progressive reveal and lightweight parallax. Classes are added only when JS is available,
// so the content remains fully visible if scripting is disabled.
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver' in window&&!reducedMotion.matches){
  const targets=[...$$('.home-about-copy,.home-about-visual,.section-heading,.business-card,.project-card,.news-card,.service-feature,.principles-grid article,.contact-layout>*,.impact-content>*')];
  targets.forEach((el,i)=>{
    el.classList.add('reveal-item');
    if(el.matches('.home-about-copy,.contact-layout>*:first-child'))el.classList.add('reveal-left');
    if(el.matches('.home-about-visual,.contact-layout>*:last-child'))el.classList.add('reveal-right');
    el.style.setProperty('--reveal-delay',`${Math.min((i%4)*55,165)}ms`);
  });
  const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{
    if(entry.isIntersecting){entry.target.classList.add('is-visible');reveal.unobserve(entry.target);}
  }),{threshold:.12,rootMargin:'0px 0px -5% 0px'});
  targets.forEach(el=>reveal.observe(el));
}

if(!reducedMotion.matches){
  const parallaxItems=$$('[data-parallax]');
  let parallaxFrame=0;
  const paintParallax=()=>{
    parallaxFrame=0;
    if(innerWidth<=768){parallaxItems.forEach(el=>el.style.setProperty('--parallax-y','0px'));return;}
    const viewport=innerHeight;
    parallaxItems.forEach(el=>{
      const rect=el.parentElement.getBoundingClientRect();
      if(rect.bottom<0||rect.top>viewport)return;
      const factor=Math.max(0,Math.min(.08,Number(el.dataset.parallax)||.04));
      const distance=(rect.top+rect.height/2-viewport/2)*factor;
      const limited=Math.max(-42,Math.min(42,distance));
      el.style.setProperty('--parallax-y',`${limited.toFixed(1)}px`);
    });
  };
  const requestParallax=()=>{if(!parallaxFrame)parallaxFrame=requestAnimationFrame(paintParallax);};
  addEventListener('scroll',requestParallax,{passive:true});
  addEventListener('resize',requestParallax,{passive:true});
  requestParallax();
}
})();
